function MHQguiObjectsOFF(handles, varargin)
%MHQguiObjectsOFF disables the gui objects in the main MOHAWQ GUI
%   %   Input
%       handles     MOHAWQ GUI handles
%       varargin    exceptions; objects to leave enabled
%
%   Copyright 2019, University of North Carolina at Chapel Hill
%   Written by: Mac Gilliland


set([handles.loadExcelFile,             ...
    handles.spotSpacing,                ...
    handles.lineSpacing,                ...
    handles.createROI,                  ...
    handles.deleteROI,                  ...
    handles.displayROI,                 ...
    handles.ROIList,                    ...
    handles.launchProfileTool,          ...
    handles.ionList,                    ...
    handles.newIon,                     ...
    handles.deleteIon,                  ...
    handles.minScaleSlider,             ...
    handles.maxScaleSlider,             ...
    handles.minScaleSliderValue,        ...
    handles.maxScaleSliderValue,        ...
    handles.moveUp,                     ...
    handles.moveDown,                   ...
    handles.detectROIs,                 ...
    handles.roiWidth,                   ...
    handles.polyOrder],                 ...
    'Enable', 'Off');

% Leave these enabled
if nargin > 1, set([varargin{:}],'Enable','On'); end

end

